### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by CDFN** [Koboo/reposilite-discord-webhook-plugin#1]
Hi, there's typo in Discord webhook screenshot. It's `Reposilioe` instead `Reposilite`. Just a small thing but decided to create issue anyway, maybe you'll want to correct this. Great job overall :+1:

**Comment by Koboo** [comment]
Hey, 
I fixed it in 44e35d986d00677a3cd6d4c5962f8d103a5378e3.

Thanks for your feedback, glad to hear that! 😄
